name: CLI Scripts Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  rvc_cli:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install dependencies
      run: |
        pip install --upgrade pip==24.0
        pip install --no-cache-dir -r requirements.txt

    - name: Install necessary models
      run: |
        python download_models.py
        python3 -m PolGen.rvc.modules.model_manager "https://huggingface.co/Politrees/Victor_Tsoi/resolve/main/Victor_Tsoi.zip?download=true" "Tsoi"

    - name: Set up test audio
      run: |
        mkdir -p audio
        wget https://huggingface.co/Politrees/audio_for_test/resolve/main/BritishEnglishUKTest5.mp3 -O audio/test.mp3

    - name: Run rvc script
      run: |
        python3 -m PolGen.rvc.infer.infer_cli rvc -i "audio/test.mp3" -m "Tsoi" -p -0.5 -ir 0 -rms 1 -f0 "rmvpe" -hop 32 -pro 0.5 -f0min 1 -f0max 1100 -f "mp3"

  tts_cli:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install dependencies
      run: |
        pip install --upgrade pip==24.0
        pip install --no-cache-dir -r requirements.txt

    - name: Install necessary models
      run: |
        python download_models.py
        python3 -m PolGen.rvc.modules.model_manager "https://huggingface.co/Politrees/Victor_Tsoi/resolve/main/Victor_Tsoi.zip?download=true" "Tsoi"

    - name: Run tts script
      run: |
        python3 -m PolGen.rvc.infer.infer_cli tts -t "e" -v "en-US-GuyNeural" -m "Tsoi" -r 0 -p -0.5 -ir 0 -rms 1 -f0 "rmvpe" -hop 32 -pro 0.5 -f0min 1 -f0max 1100 -f "mp3"
